services:
  - type: web
    name: sstyle-tehran-shirt-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /admin
        destination: /
      - type: rewrite
        source: /admin/*
        destination: /
      - type: rewrite
        source: /products/*
        destination: /
      - type: rewrite
        source: /*
        destination: /
